server:
  port: 30000
spring:
  application:
    name: wfb-service-manage
  datasource:
    url: jdbc:mysql://localhost:3306/sxx?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1023
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法