server:
  port: 32000
spring:
  application:
    name: sxx-service-mobile
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  datasource:
    url: jdbc:mysql://52.83.149.232:3306/sxx?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: sxxpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: utf-8
    cache: false #开发环境关闭缓存
    mode: LEGACYHTML5

  resources:
    static-locations: classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法
pagehelper:
  helper-dialect: mysql